spring:
    cloud:
        gcp:
            sql:
                enabled: false
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: create
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5420/youthcouncil
        username: spring
        password: spring
    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
            additional-exclude: WEB-INF/**
    thymeleaf:
        cache: false
