spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 4924686869-6lfnouaqdaed7tn3lvcpqrddjn5slime.apps.googleusercontent.com
                        clientSecret: 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
                        scope:
                            - email
                            - profile
                    facebook:
                        clientId: 230883409507790
                        clientSecret: 3e320334c91d91dbb1c3c71afddc38b1
                        scope:
                            - email
                            - public_profile
    profiles:
        active: dev # options: dev, prod
    jpa:
        show-sql: false
        open-in-view: false
        defer-datasource-initialization: true
    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
            additional-exclude: WEB-INF/**
    thymeleaf:
        cache: false
    sql:
        init:
            mode: never
#            data-locations: classpath:data.sql  comment this out once we have a data.sql file
#            schema-locations: classpath:schema.sql
server:
    port: 8081
logging:
    level:
        #    web: debug
        be.kdg.youthcouncil: debug
        #        root: debug
        #sql: debug
        org.springframework.security: DEBUG