spring:
    cloud:
        gcp:
            sql:
                enabled: false
    datasource:
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
        url: jdbc:hsqldb:file:./db/youthCouncilDB;DB_CLOSE_DELAY=-1
        username: admin
        password: admin
    jpa:
        hibernate:
            ddl-auto: create
        database: HSQL
        show-sql: true
    security:
        user:
            name: admin
            password: admin
            roles: MEMBER
#logging:
#    level:
#        root: debug
