spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: ${GOOGLE_CLIENT_ID}
                        clientSecret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - email
                            - profile
                    facebook:
                        clientId: ${FACEBOOK_CLIENT_ID}
                        clientSecret: ${FACEBOOK_CLIENT_SECRET}
                        scope:
                            - email
                            - public_profile
    profiles:
        active: ${ACTIVE_SPRING_PROFILE} # options: dev, prod, postgres (local postgres)
    jpa:
        show-sql: false
        open-in-view: false
        defer-datasource-initialization: true
    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
            additional-exclude: WEB-INF/**
    thymeleaf:
        cache: false
    sql:
        init:
            mode: never
    #            data-locations: classpath:data.sql  comment this out once we have a data.sql file
    #            schema-locations: classpath:schema.sql
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
server:
    port: 8081
logging:
    level:
        #    web: debug
        be.kdg.youthcouncil: debug
        #        root: debug
        #        sql: debug
        org.springframework.security: debug
