spring:
    cloud:
        gcp:
            sql:
                enabled: false
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5420/youthcouncil
        username: spring
        password: spring
    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
            additional-exclude: WEB-INF/**
    thymeleaf:
        cache: false

    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: ${GOOGLE_CLIENT_ID}
                        clientSecret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - email
                            - profile
                    facebook:
                        clientId: ${FACEBOOK_CLIENT_ID}
                        clientSecret: ${FACEBOOK_CLIENT_SECRET}
                        scope:
                            - email
                            - public_profile
    profiles:
        active: ${ACTIVE_SPRING_PROFILE} # options: dev, prod, postgres (local postgres)
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: create-drop
    sql:
        init:
            mode: always
    #            data-locations: classpath:data.sql  comment this out once we have a data.sql file
    #            schema-locations: classpath:schema.sql
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
server:
    host: ${CURRENT_DOMAIN}
    port: 8081
config:
    seeding:
        additional:
            active: true
            users: 300
            max:
                annoucements: 30
                actionpoints: 5
                callforideas:
                    cfi: 3
                    ideas: 50
                infopages:
                    ip: 5
                    infopageblocks: 15
        #logging:
        #    level:
        #    web: debug
        #        be.kdg.youthcouncil: debug

    #        root: debug
#        sql: debug
#        org.springframework.security: debug
