@startuml
' tested userstories
'26 7

abstract User {
    firstName : String
    lastName : String
    email : String
    password : String
    postcode : String
}

abstract Admin {

}

class GeneralAdmin {

}

class CouncilAdmin {
    
}

class Member {
    isModerator : boolean
}

class YouthCouncil {
    councilName : String
    municipalityName : String
    councilLogo : String
    councilQrCode : String
    afterElection : boolean
    pathToModulesJson : String
}

abstract Module {
    title : String
    description : String
    images : List<String>
    videos : List<String>
}

class CallForIdeas {

}

class Idea {
}

class InformativePage {

}

class ActionPoint {
    theme : String
    label : Label
}

class Annoucement {

}

class Theme {
    name : String
}

enum Label {
    NOT_INCLUDED
    INCLUDED
    IN_PROGRESS
    REALIZED
}

class NewsFeed {

}

class Reaction {
    emoji : Emoji
}

class Share {

}

enum Emoji {
    LIKE
    HEART
    ROCKET
    POOP
    SKELETON
}




GeneralAdmin --|> Admin
CouncilAdmin --|> Admin
Member --|> User
Admin --|> User


CallForIdeas --|> Module
Idea --|> Module
Idea --* CallForIdeas : ideas
ActionPoint --|> Module
Annoucement --|> Module

YouthCouncil "*"--"*" Member : CouncilMembers
YouthCouncil "*"--"*" Member : BlockedMembers
YouthCouncil "1"--"*" CouncilAdmin
YouthCouncil "1"--"*" InformativePage
InformativePage "*" -- "*" Module

YouthCouncil "1"--"*" Module : displayedModules
YouthCouncil "1"--"*" Module : defaultModules
YouthCouncil -- NewsFeed



Theme o-- ActionPoint
Theme o-- Idea

Annoucement --* NewsFeed

Module "1" -- "*" Reaction : reactions
Module "1" -- "*" Share : shares

Share "*"--"1" User
Reaction "*"--"1" User


' Start design class diagram
class PageVisit {
    page : String
    starttime : DateTime
    endtime : DateTime
}

interface UserRepository{
    save(user : User)
    delete(user : User)
    findAll() : List<User>
    findById(id : Long) : User
    findByEmail(email : String) : User
}


interface ModuleRepository{
    save(module : Module)
    delete(module : Module)
    findAll() : List<Module>
    findById(id : Long) : Module
}

interface YouthCouncilRepository{
    save(youthCouncil : YouthCouncil)
    delete(youthCouncil : YouthCouncil)
    findAll() : List<YouthCouncil>
    findById(id : Long) : YouthCouncil
}

interface UserService{
    getAllUsers() : List<User>

}
class UserServiceImpl implements UserService{
    modelMapper : ModelMapper
}
interface ModuleService{
    getAllModules() : List<Module>

}
class ModuleServiceImpl implements ModuleService{
    modelMapper : ModelMapper
}
interface YouthCouncilService{
    getAllCouncils() : List<YouthCouncil>

}
class YouthCouncilServiceImpl implements YouthCouncilService{
    modelMapper : ModelMapper
}

class ModuleController{

}

class YouthCouncilController{
}

UserServiceImpl -- UserRepository
ModuleServiceImpl -- ModuleRepository
YouthCouncilServiceImpl -- YouthCouncilRepository
YouthCouncilServiceImpl -- ModuleRepository
YouthCouncilController -- YouthCouncilService

ModuleServiceImpl -- UserRepository


@enduml