@startuml

participant ":YouthCouncilController" as YouthCouncilController
participant ":YouthCouncilService" as YouthCouncilService
participant ":ModelMapper" as ModelMapper
participant ":DisplayableRepository" as DisplayableRepository
participant "youthCouncil:YouthCouncil" as youthCouncil
participant ":YouthCouncilRepository" as YouthCouncilRepository

->YouthCouncilController : .addNewYouthCouncil(YouthCouncilDTO)
YouthCouncilController->YouthCouncilService : .addNewYouthCouncil(YouthCouncilDTO)
YouthCouncilService->ModelMapper : .map(YouthCouncilDTO, YouthCouncil.class)
YouthCouncilService<--ModelMapper : youthCouncil
YouthCouncilService-> DisplayableRepository : .findAll()
YouthCouncilService<--DisplayableRepository : displayables
YouthCouncilService-> youthCouncil: . addDefaultDisplayables(displayables)
YouthCouncilService->YouthCouncilRepository : .save(YouthCouncil)


@enduml