@startuml

participant ":YouthCouncilController" as YouthCouncilController
participant ":YouthCouncilService" as YouthCouncilService
participant ":ModelMapper" as ModelMapper
participant ":ModuleItemRepository" as ModuleItemRepository
participant "youthCouncil:YouthCouncil" as youthCouncil
participant ":YouthCouncilRepository" as YouthCouncilRepository

->YouthCouncilController : .addNewYouthCouncil(YouthCouncilDTO)
YouthCouncilController->YouthCouncilService : .addNewYouthCouncil(YouthCouncilDTO)
YouthCouncilService->ModelMapper : .map(YouthCouncilDTO, YouthCouncil.class)
YouthCouncilService<--ModelMapper : youthCouncil
YouthCouncilService-> ModuleItemRepository : .findAllDefaultModuleItems()
YouthCouncilService<--ModuleItemRepository : modulesItems
YouthCouncilService-> youthCouncil: . addDefaultModuleItems(moduleItems)
YouthCouncilService->YouthCouncilRepository : .save(YouthCouncil)


@enduml